### PR TITLE
added list storage accounts command

### PR DESCRIPTION
**Pull request by tripdubroot**
Did not add a toolbar button for this.

### CODE REVIEW

**Comment by bradygaster** [comment]
this is great. ironically i didn't have any storage accounts at the time the pr came in so i need to create some to test it out but i'm optimistic. one thing, though - let's add something other than *just* (pardon) listing the storage accounts in the quick list. how about adding "create storage account" too, then we'll have an end-to-end scenario - create, then list. next up would be something like "get connection string for storage account" and re-use the code in this PR. this is exciting though, to see the progress.

**Comment by avodovnik** [comment]
Totally digging this. 👍 

As a side question for @bradygaster - should we start introducing menu/toolbar items? Would it make sense to roughly define what goes where?

**Comment by bradygaster** [comment]
@avodovnik i think we can take toolbars and buttons on a case-by-case basis for a little while. not opposed to them but i also don't want to go crazy adding too many. also, we're limited by what icons we can use. AFAIK you can only use icons from the [Octicons](https://octicons.github.com/) library at this time.

**Comment by bradygaster** [comment]
@tripdubroot this PR is looking nearly perfect. perfect enough to take, to be frank. i do wonder one thing - is there a method like "checkNameAvailability" for validating a storage account name? if so i think we should call it prior to creating an account. sometimes people use UPPER case characters forgetting it isn't allowed, for instance. *totally not a requirement* but i wanted to throw it out as an option before taking the PR. 

i'll await your response, @tripdubroot, and if you don't think we need to implement that at this time we'll call this one good and ship 0.0.10 tonight or tomorrow. 

confirm and i'll take action.

**Comment by tripdubroot** [comment]
Good call on the SA name check. Updated the code to check.

**Comment by bradygaster** [comment]
@tripdubroot very awesome. give me the night to finish up some of my own hugely-important **real work** tasks and i'll do a functionality and code review on this. i'm pretty sure you're spot on but i want to check the logic on the "check name" thing just to be super-safe.

**Comment by bradygaster** [comment]
@tripdubroot made a few changes. basically the idea of getting storage accounts and then not doing anything with the selected one seemed weird. so i coupled the keys functionality with the retrieval functionality and made a "get connection string" command. pulling in the commit now.

**Pull request merged**
