### PR TITLE
Added new option to change behavior of opening console at startup.

### PR DESCRIPTION
**Pull request by takekazuomi**
Added azure.startAutomatically option to change a behavior of opening Azure Tools integrated console at startup. If true, open console.
This patch will be fixed https://github.com/bradygaster/azure-tools-vscode/issues/42.

## Motivation
I use vs code for git editor. In such a light usage.  Is a problem console is open at the time of start-up of the editor. Slow and focus moves.

## A question
1. I would like to disable console by default. However, this patch is the same as existing.
2. I think there is a better name for option names. This name has the same name as a similar function of PowerShell extension. I have no good idea.

### CODE REVIEW

**Comment by bradygaster** [comment]
@takekazuomi hey there! thanks for your PR, could you please check the one i just accepted from @stuartleeks that solves the same issue? i think his contribution and yours are relatively similar, and i just accepted his as he'd pinged me on twitter about it. 

hopefully @stuartleeks has the same issue you have and has fixed it.

**Comment by takekazuomi** [comment]
I checked. 
https://github.com/bradygaster/azure-tools-vscode/pull/49
It is the same. Let's close this PR. Thank you.

**Comment by bradygaster** [comment]
@takekazuomi thanks so much for the contribution! if you want to contribute, i have a few huge features i'd love to suggest if you have cycles.

**Comment by takekazuomi** [comment]
I use vscode and azure everyday. It is a wonderful product. What is your suggestion? I am interested.

**Comment by bradygaster** [comment]
glad to hear it @takekazuomi! i agree with you and can't get enough of azure + vscode and feel the combination is an excellent one. we have a few more features i'd like to implement over the upcoming few weeks, and if you're willing to contribute i'd be happy to assign some of the issues in the repository to you, as well as maybe creating a few new ones to see if you'd find any interesting enough to work on. game?

**Comment by takekazuomi** [comment]
I have browsed the current Issue. I am interested in supporting documentdb.
I will spend my weekend's  about vsat documentdb support.

**Comment by bradygaster** [comment]
@takekazuomi that sounds good. go s-l-o-w on it, okay? Let's do provisioning first, then once that's done we'll evaluate other features with their team to make sure we're helping.

**Pull request closed without merging**
